export default {
  LOGOUT_USER: 'app/user/LOGOUT_USER',
  REQUEST_FIND_USER_BY_ID: 'app/user/REQUEST_FIND_USER_BY_ID',
  SUCCESS_FIND_USER_BY_ID: 'app/user/SUCCESS_FIND_USER_BY_ID',
  FAILURE_FIND_USER_BY_ID: 'app/user/FAILURE_FIND_USER_BY_ID',
  REQUEST_VALIDATE_USER: 'app/user/REQUEST_VALIDATE_USER',
  SUCCESS_VALIDATE_USER: 'app/user/SUCCESS_VALIDATE_USER',
  FAILURE_VALIDATE_USER: 'app/user/FAILURE_VALIDATE_USER',
  REQUEST_CREATE_POST: 'posts/createPostRequest',
  SUCCESS_CREATE_POST: 'posts/createPostSuccess',
  FAILURE_CREATE_POST: 'posts/createPostFailure',
  REQUEST_FIND_POSTS: 'posts/findPostRequest',
  SUCCESS_FIND_POSTS: 'posts/findPostSuccess',
  FAILURE_FIND_POSTS: 'posts/findPostFailure',
  REQUEST_UPDATE_POST: 'posts/updatePostRequest',
  SUCCESS_UPDATE_POST: 'posts/updatePostSuccess',
  FAILURE_UPDATE_POST: 'posts/updatePostFailure',
  DELETE_POST: 'posts/deletePostRequest',
};
